services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ranking_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    ports:
      - "8004:8000"
    environment:
      APP_NAME: "Paulinian Student Government Ranking System"
      APP_ENV: local
      APP_KEY: base64:X27CkTB9aLL01FQbGDbuowR86oj/oKsICClYZWtOmiU=
      APP_DEBUG: true
      APP_URL: http://localhost:8004

      LOG_CHANNEL: stack

      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ranking_sys
      DB_USERNAME: ranking_sys
      DB_PASSWORD: secret

      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120

    command: php artisan serve --host=0.0.0.0 --port=8000
    networks:
      - ranking_net

  mysql:
    image: mysql:8.0
    container_name: ranking_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ranking_sys
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ranking_sys
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - ranking_net

volumes:
  mysql_data:

networks:
  ranking_net: